# Generated by Django 5.1.1 on 2024-09-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empanadas', '0002_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='empanada',
            name='image',
            field=models.ImageField(default='imagesEmpanadas/default.png', upload_to='imagesEmpanadas/'),
        ),
    ]
